/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api.paystack.webhook'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack/webhook',
  path: '/api/paystack/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/shop': typeof ShopRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/shop': typeof ShopRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/shop': typeof ShopRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/dashboard'
    | '/shop'
    | '/payment/callback'
    | '/api/paystack/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/dashboard'
    | '/shop'
    | '/payment/callback'
    | '/api/paystack/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/dashboard'
    | '/shop'
    | '/payment/callback'
    | '/api/paystack/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  ShopRoute: typeof ShopRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/webhook': {
      id: '/api/paystack/webhook'
      path: '/api/paystack/webhook'
      fullPath: '/api/paystack/webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  ShopRoute: ShopRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
